# _config.yml
title: lib-bash – Bash Libraries
description: Documentation generated via Jekyll GitHub Action
theme: jekyll-theme-hacker

# Other configurations
markdown: kramdown
show_downloads: true
#strict_front_matter: true
collections:
  lib:
    output: true
    sort_by: title
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-picture-tag
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
  - kramdown-parser-gfm
# Default configuration for collections
defaults:
  - scope:
      path: ""
      type: lib
    values:
      layout: default
