name: "Bats: Bash Tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Bats tests
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux
        run: |
          bash -c "./tests/bats/bin/bats --print-output-on-failure ./tests"
