name: "Bats: Bash Tests"

on:
  push:
    branches:
      - main
    paths:
      - "**/*.sh"
      - "tests/**"
      - ".gitmodules"
      - "!demo/**"
      - ".github/workflows/bats.yml"
  pull_request:
    types: [ready_for_review, synchronize]
    paths:
      - "**/*.sh"
      - "tests/**"
      - ".gitmodules"
      - "!demo/**"
      - ".github/workflows/bats.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Bats tests
        shell: 'script -q -e -c "bash {0}"' # work around tty issues
        env:
          TERM: linux
        run: |
          bash -c "./lib/test/bats/core/bin/bats --print-output-on-failure ./tests"
