name: "Bats: Bash Tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run Bats tests
        run: bats tests
