name: Interactive Command Execution

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to execute"
        required: true
        default: "demo/all-demos.sh"
      os:
        description: "Operating system to run the command on"
        required: true
        default: "macos-latest"
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
      install_gnu_tools:
        description: "Install GNU tools on macOS"
        required: true
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  run-command:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install GNU tools on macOS
        if: ${{ inputs.install_gnu_tools }}
        run: |
          bin/gnu-install.sh

      - name: Execute command
        run: ${{ inputs.command }}
