name: "Release – Complete"
# concurrency: Ensures that for one branch the workflow is not running multiple
# times at the same time as we will get trouble with the versions and pushes.
concurrency: ci-${{ github.ref }}

on:
  push:
    branches:
      - main
    paths:
      - ".version"

permissions:
  contents: write

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ steps.version.outputs.next_version }}
    steps:
      - name: Checkout repository
        id: checkout-version
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .version
      - name: Read Version
        id: version
        run: |
          echo "next_version=$(cat .version)" >> $GITHUB_OUTPUT
  release-tag:
    runs-on: ubuntu-latest
    needs:
      - read-version
    outputs:
      tag-name: ${{ steps.tag-release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        id: checkout-tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Tag Release
        id: tag-release
        run: |
          next_version="${{ needs.read-version.outputs.next-version }}"
          tag_name="v${next_version}"
          git tag -a -m "Release ${next_version}" "${tag_name}"
          git push origin "${tag_name}"
          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT
  release-artifacts:
    # The Pull Request is merged. Now we can perform the release.
    runs-on: ubuntu-latest
    needs:
      - read-version
      - release-tag
    outputs:
      release-artifacts-url: ${{ steps.upload-artifacts.outputs.artifact-url }}
    steps:
      - name: Checkout repository
        id: checkout-perform
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.release-tag.outputs.tag-name }}
          sparse-checkout: |
            .version
            README.md
            UNLICENSE
            lib_*.sh
      - name: Upload Release Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib-bash-${{ needs.read-version.outputs.next-version }}
          include-hidden-files: true
          path: |
            .version
            README.md
            UNLICENSE
            lib_*.sh
  release-complete:
    runs-on: ubuntu-latest
    needs:
      - release-tag
      - release-artifacts
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release-url: ${{ steps.create-release.outputs.url }}
    steps:
      - name: Create Release
        id: create-release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ needs.release-artifacts.outputs.release-artifacts-url }}
          tag_name: ${{ needs.release-tag.outputs.tag-name }}
          name: ${{ needs.release-tag.outputs.tag-name }}
          body: "Release ${{ needs.release-tag.outputs.tag-name }}"
          draft: false
          prerelease: false
  release-summary:
    # Output Markdown Report to $GITHUB_STEP_SUMMARY
    runs-on: ubuntu-latest
    needs:
      - read-version
      - release-tag
      - release-complete
    steps:
      - name: summary
        id: summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          # ${{ github.workflow }} (${{ github.event.inputs.release_type }})

          * **Version**: ${{ needs.read-version.outputs.next-version }}
          * [Release ${{ needs.release-tag.outputs.tag-name }}](
            ${{ needs.release-complete.outputs.release-url }}
            )
