name: "Release – Prepare"
# concurrency: Ensures that for one branch the workflow is not running multiple
# times at the same time as we will get trouble with the versions and pushes.
concurrency: ci-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: |
          Choose a release type.
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

run-name: |
  ${{ github.workflow }} (${{ github.event.inputs.release_type }})

permissions:
  contents: write
  pull-requests: write

jobs:
  release-prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout-prepare
        uses: actions/checkout@v4
      - name: Update Version
        id: version
        run: |
          echo "prev_version=$(cat .version)" >> $GITHUB_OUTPUT
          bin/version.sh ${{ github.event.inputs.release_type }}
          echo "next_version=$(cat .version)" >> $GITHUB_OUTPUT
      - name: Update Documentation
        id: update-docs
        run: |
          echo "Update documentation for version ${{ steps.version.outputs.next_version }}"
          bin/docs.sh
      - name: Create pull request
        id: create-pull-request
        # https://github.com/peter-evans/create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "ci(release): Update version to ${{ steps.version.outputs.next_version }}"
          branch: release/${{ steps.version.outputs.next_version }}
          title: "Release ${{ steps.version.outputs.next_version }}"
          body: "This pull request updates the version to ${{ steps.version.outputs.next_version }}."
          base: main
          labels: |
            ignore-for-release
      - name: Summary
        id: summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          # Release Prepare Summary

          - **Previous Version**: ${{ steps.version.outputs.prev_version }}
          - **Next Version**: ${{ steps.version.outputs.next_version }}
          - **Pull Request Branch**: ${{ steps.create-pull-request.outputs.pull-request-branch }}
          - **Pull Request Number**: ${{ steps.create-pull-request.outputs.pull-request-number }}
          - **Pull Request URL**: [${{ steps.create-pull-request.outputs.pull-request-url }}](${{ steps.create-pull-request.outputs.pull-request-url }})
          EOF
