name: shfmt

on:
  push:
    branches:
      - main
    paths:
      - "**/*.sh"
      - ".github/workflows/shfmt.yml"
  pull_request:
    types: [ready_for_review, synchronize]
    paths:
      - "**/*.sh"
      - ".github/workflows/shfmt.yml"
  workflow_dispatch:

permissions: {}

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt

      - name: Run shfmt
        run: |
          shfmt --diff .
