name: System Tests Demo

on:
  push:
    branches:
      - main
    paths:
      - "**/*.sh"
      - ".github/workflows/system-tests-demo.yml"
  pull_request:
    types: [ready_for_review, synchronize]
    paths:
      - "**/*.sh"
      - ".github/workflows/system-tests-demo.yml"
  workflow_dispatch:

jobs:
  run-demos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        install_gnu_tools: [true, false]
        exclude:
          - os: ubuntu-latest
            install_gnu_tools: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install GNU tools on macOS
        if: ${{ matrix.os == 'macos-latest' && matrix.install_gnu_tools }}
        run: |
          bin/gnu-install.sh

      - name: Set ASSUME_GNU environment variable
        run: echo "ASSUME_GNU=${{ matrix.install_gnu_tools }}" >> $GITHUB_ENV

      - name: Run all demos
        run: |
          demo/all-demos.sh
